TeX Live zaprasza

   TeX Live oferuje pel/ny system TeX-a dla wielu róznych systemów
   operacyjnych, Unix, Macintosh, Windows i wielu innych. Znajdziemy tu
   programy do skl/adu tekstów, programy do przegladania i drukowania
   dokumentów TeX-owych w wielu jezykach oraz bogate kolekcje makr i
   fontów.

   Dystrybucja zawiera obszerna dokumentacje TeX-a, a takze dokumentacje
   towarzyszace poszczególnym pakietom oprogramowania.

   Infomacje licencyjne (w jezyku angielskim) mozna znalezc w plikach
   tekstowych [1]LICENSE.TL oraz [2]LICENSE.CTAN.

  Od czego zaczac

   Przed rozpoczeciem instalacji zalecamy wydrukowac i przeczytac
   Przewodnik po TeX Live. Prowadzi on krok po kroku przez instalacje,
   znajdziemy tam opis gl/ównego drzewa katalogów i duzo wiecej.

   Gdy instalujemy z pl/ytki DVD, wersje Przewodnika w kilku jezykach
   dostepne sa w podkatalogu [3]texlive-doc.

   Po zainstalowaniu systemu, Przewodnik w jezyku angielskim w formacie
   [4]html i [5]pdf znajdziemy w [6]texmf-dist/doc/texlive/. Tam tez sa
   dostepne inne wersje jezykowe Przewodnika, w tym polska.

   Dol/aczylismy równiez liste odnosników do [7]dokumentacji HTML and PDF
   programów i pakietów zawartych w instalacji.

   Jesli instalujemy TeX Live z internetu, powyzsze odnosniki nie
   dzial/aja. W tym przypadku nalezy siegnac do dokumentacji tutaj: [8]TeX
   Live documentation on the Internet.

   Lista najwazniejszych zmian w biezacej edycji znajduje sie na koncu
   dokumentacji w rozdziale Historia.

  Instalacja

   Skrypt instalacyjny nazywa sie install-tl (install-tl-windows.bat dla
   Windows) i ma dwa tryby pracy:

   -gui (domyslny dla Windows i Macs), który uzywajac interfejsu
          graficznego, bez zbednych zapytan instaluje cal/y system, ale
          pozwala równiez na wybranie instalacji zaawansowanej.

   -no-gui (domyslny dla wszystkich innych systemów), który w trakcie
          instalacji umozliwia wybór wszystkich dostepnych opcji za pomoca
          prostego interfejsu tekstowego.

   Do dodawania/usuwania pakietów, aktualizacji z internetu oraz innych
   czynnosci konfiguracjnych mozna uzyc programu tlmgr (TeX Live Package
   Manager), który tak jak program instalacyjny, ma dwa tryby pracy
   (graficzny oraz tekstowy).

   Szczegól/owe informacje o [9]install-tl i [10]tlmgr uzyskamy
   uruchamiajac je z linii polecen z parametrem --help. Wiecej informacji
   mozna znalezc w dokumentacji, o której byl/a mowa powyzej.

  Przydatne linki

   Na koniec kilka adresów stron internetowych, na których mozna znalezc
   wiecej informacji o TeX-u. Nie sa one dol/aczone do TeX Live:

     * [11]tug.org/begin.html - dla poczatkujacych uzytkowników TeX-a
       i/lub potrzebujacych podstawowych o nim informacji.
     * [12]tug.org/interest.html - gl/ówna lista internetowych zasobów
       TeX-owych, systemów, pakietów, fontów i wielu innych, takze
       dokumentacji.
     * [13]tug.org/ctan.html - jeden z adresów Comprehensive TeX Archive
       Network (CTAN), który zawiera swiatowe archiwa TeX-owe.
     * [14]tug.org/usergroups.html - lista grup uzytkowników systemu TeX
       na cal/ym swiecie, wraz z danymi kontaktowymi. Goraco zachecamy do
       przyl/aczenia sie do wybranej grupy uzytkowników, a takze
       wspomagania prac przy TeX Live oraz innych aktywnosci.

    Mil/ego TeX-owania!
     __________________________________________________________________

   [15]TeX Live home page.

References

   1. file:../LICENSE.TL
   2. file:../LICENSE.CTAN
   3. file:../texlive-doc
   4. file:../texmf-dist/doc/texlive/texlive-en/texlive-en.html
   5. file:../texmf-dist/doc/texlive/texlive-en/texlive-en.pdf
   6. file:../texmf-dist/doc/texlive/texlive-en
   7. file:../doc.html
   8. https://tug.org/texlive/doc.html
   9. https://tug.org/texlive/doc/install-tl.html
  10. https://tug.org/texlive/tlmgr.html
  11. https://tug.org/begin.html
  12. https://tug.org/interest.html
  13. https://tug.org/ctan.html
  14. https://tug.org/usergroups.html
  15. https://tug.org/texlive/
